python main.py \
  --experiment_description ACON_SANITY \
  --run_description UCIHAR_clean \
  --da_method ACON \
  --dataset UCIHAR \
  --data_path ./data \
  --device cpu \
  --lr 0.01 \
  --cls_trade_off 1 \
  --domain_trade_off 1 \
  --entropy_trade_off 0.01 \
  --align_t_trade_off 1 \
  --align_s_trade_off 1 \
  --shuffle \
  --debug